### ISSUE TITLE
FR11. User settings

### ISSUE THREAD

**Issue by kratkiewiczk** [WSU-4110/WSU-ReTraceMe#14]
|FR11. User settings|
|---|
|**Goal**: Provide users options to customize how they use the app
**Stakeholders:** All|
| **Description:** A user can go into the settings and choose whether or not they wish to have some features be on or off. This will allow users to modify the app to their liking in a way which is useful to them. |
| **Origin:** Came up during the discussion of functional/Non Functional requirements.|
| **Version:** 1.0 |
|**Date:** 09/18/2019
| **Priority:** Medium |

**Comment by w1-ll** [comment]
User settings were always planned but never got around to it before the due dat
