### ISSUE TITLE
NR4. Cross-browser compatibility

### ISSUE THREAD

**Issue by Hasan-Ahmad8** [WSU-4110/WSU-ReTraceMe#19]
|NR4. Cross-browser compatibility|
|---|
|**Goal**: Ensure compatibility amongst the most commonly used web-browsers
**Stakeholders:** All|
| **Description:** Pick a common browser give compatibility to multiple users|
| **Origin:** Came up during discussion of functional/non functional requirements.|
| **Version:** 1.0 |
|**Date:** 09/19/2023
| **Priority:**  Mid to High|

**Comment by w1-ll** [comment]
Works on most browsers, but Chrome is somewhat buggy because it has trouble with allowing location tracking
