### ISSUE TITLE
NR6. Browser Compatibility

### ISSUE THREAD

**Issue by Hasan-Ahmad8** [WSU-4110/WSU-ReTraceMe#21]
|NR6. Browser Compatibility|
|---|
|**Goal**: Allows for use on different style browsers
**Stakeholders:** All|
| **Description:** Users can still access the web-app no matter the browser style.|
| **Origin:** |
| **Version:** 1.0 |
|**Date:** 09/19/2023
| **Priority:** High |

**Comment by w1-ll** [comment]
Works on most browsers, but Chrome is somewhat buggy because it has trouble with allowing location tracking.
Link to issue:
