### ISSUE TITLE
FR5. Waypoints set by users

### ISSUE THREAD

**Issue by kratkiewiczk** [WSU-4110/WSU-ReTraceMe#6]
|FR5.  Waypoints set by users |
|---|
|**Goal**: Have a customizable interval on when the waypoints should be set
**Stakeholders:** All users|
| **Description:** When a user enters the app, waypoints will be set every so often when a certain criteria is met. However, if the user needs or wishes to place a waypoint somewhere that is significant to them but does not meet the criteria for the automatic waypoint to be set. They will have the option to override and manually place a waypoint. |
| **Origin:** Specification came up when a non-team member brought up a good point during the first presentation..|
| **Version:** 1.0  |  
|**Date:** 9/18/2023
|  **Priority:**  Medium |

**Comment by Schaubt** [comment]
|FR1.  Waypoints set by users |
|---|
|**Goal**: Have a customizable interval on when the waypoints should be set
**Stakeholders:** All users|
| **Description:** When a user enters the app, waypoints will be set every so often when a certain criteria is met. However, if the user needs or wishes to place a waypoint somewhere that is significant to them but does not meet the criteria for the automatic waypoint to be set. They will have the option to override and manually place a waypoint. |
| **Origin:** Specification came up when a non-team member brought up a good point during the first presentation..|
| **Version:** 1.0  |  
|**Date:** 9/18/2023
|  **Priority:**  Medium |
