### ISSUE TITLE
FR8. Timestamps on waypoints

### ISSUE THREAD

**Issue by Hasan-Ahmad8** [WSU-4110/WSU-ReTraceMe#7]
|FR8. Timestamps on waypoints |
|---|
|**Goal**: Mark the points where you were last seen
**Stakeholders:** All|
| **Description:** Wherever the user’s last waypoint was marked, there should be a timestamp to the marked location so it can be easier to retrace your steps |
| **Origin:** This came up just in case someone forgot which building they came from|
| **Version:** 1.0 |  
|**Date:** 09/18/2023
|  **Priority:** Medium |

**Comment by w1-ll** [comment]
Timestamps are added
